import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "./components/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClientProvider>
        <body className={inter.className}>{children}</body>
      </ClientProvider>
    </html>
  );
}
